services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=May123@321abc
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    depends_on:
      - mssql
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: >
      sh -c "sleep 15 && npm start"

  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad
    depends_on:
      - mssql
    ports:
      - "3000:3000"
    environment:
      # Admin user for logging into SQLPad UI
      SQLPAD_ADMIN: admin@example.com
      SQLPAD_ADMIN_PASSWORD: superStrong1

      # Optional: log levels
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn

      # Predefined connection to your MSSQL container
      SQLPAD_CONNECTIONS__sqldemo__name: "MSSQL Demo"
      SQLPAD_CONNECTIONS__sqldemo__driver: sqlserver
      SQLPAD_CONNECTIONS__sqldemo__host: mssql
      SQLPAD_CONNECTIONS__sqldemo__database: appdb
      SQLPAD_CONNECTIONS__sqldemo__username: sa
      SQLPAD_CONNECTIONS__sqldemo__password: May123@321abc
    volumes:
      - sqlpad_data:/var/lib/sqlpad

volumes:
  mssql_data:
  sqlpad_data:
